name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create Virtual Environment
      run: python -m venv venv

    - name: Activate Virtual Environment
      run: source venv/bin/activate

    - name: Install pytest
      run: |
        source venv/bin/activate
        pip install pytest

    - name: Install selenium
      run: |
        source venv/bin/activate
        pip install selenium

    - name: Install faker
      run: |
        source venv/bin/activate
        pip install faker

    - name: Install pytest-html
      run: |
        source venv/bin/activate
        pip install pytest-html

    - name: Generate HTML Report
      run: |
        source venv/bin/activate
        pytest -v --html=report.html \
                --verbose \
                --showlocals \
                --durations=0

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: TestReportsSE-Exemplo
        path: report.html