name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create Virtual Environment
      run: python -m venv venv

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium faker pytest-html

    - name: Esteira de testes e Generate Reports
      run: |
        pytest -v --html=report.html --junitxml=test-results.xml \
                --self-contained-html \
                --capture=sys \
                --verbose \
                --showlocals \
                --durations=0 

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestReportsSE-Exemplo_html
        path: report.html

    - name: Upload XML Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestResultsSE-Exemplo_xml
        path: test-results.xml